name: Test
'on':
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install test dependencies
        run: |
          python -m pip install --disable-pip-version-check editorconfig-checker
          make install-python-dependencies

      - name: Run tox
        run: |
          make lint-editorconfig
          make test-python
